### ISSUE TITLE
Stringify on array of objects runs into error

### ISSUE THREAD

**Issue by shahnenigans** [squirrelchat/smol-toml#14]
```
let test = [{name: "hello", test: "world", number: 3}, {name: "efe", test: "wef", number: 4}]  
console.log(stringify(test))
```
results in "ERROR TypeError: stringify can only be called with an object"  

It would be great it that worked.

Otherwise it is a really great package. Thank you.

**Comment by cyyynthia** [comment]
I'm inclined to classify this as a "working as intended" thing, considering how TOML works.

Stringify is producing a valid TOML document and this means it cannot itself be an array, since the "root" of a TOML document is by definition table (unlike in JSON where the root can be an array)

However I'm assuming the desired behavior would be to stringify the value as a TOML value rather than a full document, right? (And possibly also have the possibility to parse a value rather than the whole document)

This would be a new feature as the stringify method is really intended for producing valid documents, which an array isn't.

**Comment by shahnenigans** [comment]
Oh I derped. So if I just did this it would have worked.
```
    let test = {somedata: [{name: "hello", test: "world", number: 3}, {name: "efe", test: "wef", number: 4}]}
    console.log(stringify(test))
```  
Thank you very much for clarification.
