### ISSUE TITLE
Warning error in Angular 17 saying it is not ES6 modules .

### ISSUE THREAD

**Issue by Easy-Cloud-in** [squirrelchat/smol-toml#20]
Is the smol-toml ES6 module compatible? When trying to` ng server` or` ng built` in Angular 17  
it throws a warning

Warning: E:\ec-projects\angular-v17-projects\htxpp-web-app-v1\src\app\modules\landing\aboutus\aboutus.component.ts depends on'smol-toml'. CommonJS or AMD dependencies can cause optimization bailouts.

Is it ES6 and Typescript compatible?

**Comment by cyyynthia** [comment]
Hi there! This library is compatible with ESM style imports and provides TypeScript declaration files (since it's itself written in TypeScript!)

This warning from Angular comes from the fact this library is packaged as a ESM-compatible CommonJS module, to maximize interoperability. As CJS is more tricky to treeshake than ESM, Angular made the choice to warn when CJS is involved.

This warning can safely be ignored (and silenced), the library will work without issues. I'm also pretty sure there will be no treeshaking issues either, as this library does express its exports in a way recognized by all major build tools as treeshakable. Feel free to let me know if you encounter any issues!

**Comment by Easy-Cloud-in** [comment]
@cyyynthia  Thank you for responding. The library works like a charm, and there are no issues with it. 
Only my Angular 17 throws a warning at the time of build or serve.  I have to suppress this error in my config file.
