### ISSUE TITLE
Explicit type for parse

### ISSUE THREAD

**Issue by sleewoo** [squirrelchat/smol-toml#5]
Hello,
congrats on grounding a new parser, looks promising with specs/tests etc.

Would you consider generic type for `parse` function rather than returning `Record<string, TomlPrimitive>`?

```ts
const data = parse<MyType>(src)
```
would return `Record<string, MyType>`

thanks

**Comment by sleewoo** [comment]
supposed to avoid awkward syntax like

```ts
const data = parse(src) as Record<string, MyType>
```

**Comment by cyyynthia** [comment]
I definitely can, but I have mixed feelings about it. While convenient, this would only move the non-type-safe `as T` inside the library code, and I'm not a fan of this.

Semantically speaking, the library can only guarantee that the object it returns is a record of any string key and any TOML primitive as a value. The generic would only be an alternative syntax that "hides" the fact the parsed object is cast without validation.

This might be fine for apps dealing with trusted data, but even then for things like config I'd recommend using a schema validator to check if the config is valid - there's excellent validators out there which will return a typed object if it complies with a given schema, or give a helpful runtime error otherwise.

Lastly, moving the cast away of your code makes it harder to detect statically with tools like eslint, and may cause subtle bugs which are hard to troubleshoot since TypeScript's type safety guarantees have been broken.

**Comment by sleewoo** [comment]
makes sense, except when `MyType` comes from a validator :)

**Comment by cyyynthia** [comment]
A lot of (modern) type-safe validators such as Valibot or Zod will automatically refine the type once it passed validation, effectively acting as a safe type-cast.

```ts
const configSchema = object({
  ...
})

const parsed = parse(toml)
// parsed is a simple Record, only thing smol-toml can guarantee
const config = configSchema.parse(parsed)
// config is strongly and safely typed, or an error has been thrown at this point (config is invalid)
```

This strong type safety guarantee is the ideal case, and I feel like using a generic at parse level to specify output type is not a correct use of generics and reduces type safety. Still possible to cast using `as` or with the alternative syntax `const cfg = <MyType> parse(...)` if you're not in a TSX file. Both of these syntax clearly label the intent to cast which I believe is a very important semantic here.

**Comment by sleewoo** [comment]
you perfectly right! thanks

**Comment by fadeevab** [comment]
@cyyynthia I believe your comment should be in the README (and/or in the tests/examples): I spent tons of time figuring out a correct approach to _finally_ finish parsing a TOML produced by your library into a typed object.
