### ISSUE TITLE
Automated Testing and Deployment

### ISSUE THREAD

**Issue by Exponential-Workload** [squirrelchat/smol-toml#7]
It may be useful to use CI (ie [Github Actions](https://docs.github.com/en/actions)) to perform automated testing, to make sure PRs and other types of code changes don't break anything.

It may also make sense to introduce some kind of CD for "nightly"-style deployments deploying to npm on each commit (as an example using [NPM Tags](https://docs.npmjs.com/cli/v6/commands/npm-dist-tag)).

**Comment by cyyynthia** [comment]
This is something I've been thinking of and that I usually setup right away (especially the CI part). The problem here is that the tests are not exceptionally good and while I used them for the bulk of the implementation, a lot of cases are only covered by the full `toml-test` suite which is much more difficult to automate due to the compliance being not 100% and some tests requiring at the time slight modifications as mentioned in the readme.

It'd be a nice to have, but the tests written specifically for the lib (rather than toml-test itself) would need some extra care before tests are fully testing the lib. That being said they could be used as-is for the time being.

As for continuous delivery I want to make it auto-package new versions when I publish new releases on GitHub (so still a manual release but with automated push to npm), but I don't think the lib is large enough to justify the overhead of a nightly push, especially since while I mostly push directly to the default branch since there's no additional fulltime maintainer besides me, the workflow here should be pushing to a new branch and opening a PR to merge changes.

I get the wish for PRs to "land faster" using this mechanism but it's quite unhealthy to rely on that in most cases and have only very rare cases where it is beneficial. I'd consider making sure the package is installable as a git dependency easier than dealing with nightly pushes: it's virtually the same thing without the push requirement
